package models

import com.googlecode.mapperdao._

/**
 * The Class Job.
 *
 * @author Nguyen Duc Dung
 * @since 2/19/13, 9:21 AM
 *
 */
case class Job(title: String)

object Job extends Entity[Long, SurrogateLongId, Job] {
  val id = key("id") autogenerated (_.id)
  val title = key("title") to (_.title)

  def constructor(implicit m: ValuesMap) = new Job(title) with SurrogateLongId {
    val id: Long = Job.id
  }
}

