package models

import com.googlecode.mapperdao._
import org.joda.time.DateTime

/**
 * The Class User.
 *
 * @author Nguyen Duc Dung
 * @since 2/18/13, 4:32 PM
 *
 */
case class User(
                 username: String,
                 password: String,
                 email: Option[String] = None,
                 firstName: String,
                 lastName: String,
                 phone: String,
                 address: String,
                 role: String,
                 dob: DateTime
                 )

object User extends Entity[Long, SurrogateLongId, User] {
  val id = key("id") autogenerated (_.id)
  val username = column("username") to (_.username)
  val password = column("password") to (_.password)
  val email = column("email") option (_.email)
  val firstName = column("firstName") to (_.firstName)
  val lastName = column("lastName") to (_.lastName)
  val phone = column("phone") to (_.phone)
  val address = column("address") to (_.address)
  val role = column("role") to (_.role)
  val dob = column("dob") to (_.dob)

  def constructor(implicit m: ValuesMap) = new User(
    username = username,
    password = password,
    email = email,
    firstName = firstName,
    lastName = lastName,
    phone = phone,
    address = address,
    role = role,
    dob = dob
  ) with SurrogateLongId {
    override val id: Long = User.id
  }
}